<h3 align="center" style="color:blue">Codebasics Python Course: Numpy Exercise</h3>

Below two numpy arrays are given with following columns. 

* Employee Details (1) Employee ID (2) Department (3) Salary
* Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed

Using these two arrays you need to complete set of tasks which are given in the notebook cells (along with hints)

In [28]:
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])

### Task 1: Merge above two numpy arrays using np.hstack

In [4]:
# write code here
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])
Details = np.hstack((employee_details, performance_metrics))
print(Details)

[['101' 'Sales' '55000' 'Satya Nadella' '101' '85' '5']
 ['102' 'HR' '52000' 'Emily Johnson' '102' '78' '3']
 ['103' 'IT' '72000' 'Fatima Razaak' '103' '92' '7']
 ['104' 'Sales' '60000' 'John Smith' '104' '88' '6']
 ['105' 'IT' '68000' 'Priya Singh' '105' '79' '4']
 ['106' 'HR' '54000' 'Li Wei' '106' '81' '5']
 ['107' 'IT' '71000' 'Michael Brown' '107' '91' '8']
 ['108' 'Sales' '59000' 'Sunita Sharma' '108' '77' '4']
 ['109' 'HR' '53000' 'Chen Wei' '109' '83' '4']]


### Task 2: Print All the Salaries

In [11]:
# write code here
Details = np.hstack((employee_details, performance_metrics))
salaries = Details[:,2] # Printing all salaries in the 2nd column, by accessing all elements in the rows
print(salaries)


['55000' '52000' '72000' '60000' '68000' '54000' '71000' '59000' '53000']


### Task 3:  Print All the Salaries in Ascending Order

In [4]:
# write code here
import numpy as np

# Employee Details (1) Employee ID (2) Department (3) Salary
employee_details = np.array([
    [101, 'Sales', 55000, 'Satya Nadella'],  
    [102, 'HR', 52000, 'Emily Johnson'],    
    [103, 'IT', 72000, 'Fatima Razaak'],        
    [104, 'Sales', 60000, 'John Smith'],    
    [105, 'IT', 68000, 'Priya Singh'],      
    [106, 'HR', 54000, 'Li Wei'],           
    [107, 'IT', 71000, 'Michael Brown'],    
    [108, 'Sales', 59000, 'Sunita Sharma'], 
    [109, 'HR', 53000, 'Chen Wei']          
])

# Performance Metrics (1) Employee ID (2) Performance Score (out of 100) (3) Number of Projects Completed
performance_metrics = np.array([
    [101, 85, 5],
    [102, 78, 3],
    [103, 92, 7],
    [104, 88, 6],
    [105, 79, 4],
    [106, 81, 5],
    [107, 91, 8],
    [108, 77, 4],
    [109, 83, 4]
])
Details = np.hstack((employee_details, performance_metrics))
salaries = Details[:,2].astype(int) 
sorted_salaries = np.sort(salaries) # Printing salaries in ascending order
desorted_salaries = salaries[::-1]
print(sorted_salaries)

[52000 53000 54000 55000 59000 60000 68000 71000 72000]


In [7]:
## Printing salaries in descending order
desorted_salaries = salaries[::-1]
print(desorted_salaries)

[53000 59000 71000 54000 68000 60000 72000 52000 55000]


### Task 4:  Iterate through entire array and print only employee id and name

In [10]:
# write code here
Details
required = Details[:,1]
required

array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U21')

### Task 5: Print performance score of all the employees

In [12]:
# write code here
Details
individual_score = performance_metrics[:,1]
print(individual_score)

[85 78 92 88 79 81 91 77 83]


### Task 6: Convert these scores to float type by using astype(float) function

In [13]:
# write code here
# Take note of the astype function, used for convert data types.
Details
individual_score = performance_metrics[:,1].astype(float)
print(individual_score)

[85. 78. 92. 88. 79. 81. 91. 77. 83.]


### Task 7:  Now print the average performance score of all the employees

In [19]:
# write code here
average_performance_score = np.mean(individual_score)
print(average_performance_score)

83.77777777777777


### Task 8:  Print all the unique departments. You can use np.unique function for this

In [17]:
# first print departments from all the records
departments = employee_details[:,1]
departments
# write code here

array(['Sales', 'HR', 'IT', 'Sales', 'IT', 'HR', 'IT', 'Sales', 'HR'],
      dtype='<U21')

In [18]:
# now print unique departments
unique_departments = np.unique(departments)
unique_departments
# write code here

array(['HR', 'IT', 'Sales'], dtype='<U21')

### Task 9: Print average salary in HR department

In [14]:
# First print all the records in HR department
employee_details

# write code here

array([['101', 'Sales', '55000', 'Satya Nadella'],
       ['102', 'HR', '52000', 'Emily Johnson'],
       ['103', 'IT', '72000', 'Fatima Razaak'],
       ['104', 'Sales', '60000', 'John Smith'],
       ['105', 'IT', '68000', 'Priya Singh'],
       ['106', 'HR', '54000', 'Li Wei'],
       ['107', 'IT', '71000', 'Michael Brown'],
       ['108', 'Sales', '59000', 'Sunita Sharma'],
       ['109', 'HR', '53000', 'Chen Wei']], dtype='<U21')

In [15]:
# Now from these records only print  the salary column. Convert that to float using astype(float) function
salary = employee_details[:,2].astype(float)
print(salary)
# write code here

[55000. 52000. 72000. 60000. 68000. 54000. 71000. 59000. 53000.]


In [16]:
# Take an average of this column using np.mean() function
average_salary = np.mean(salary)
print(average_salary)
# write code here

60444.444444444445
