In [1]:
import numpy as np
arr = np.array([1,2,3,5])
print(arr)

[1 2 3 5]


In [3]:
print(np.__version__)

2.0.1


#### Comparing size of bytes occupied by lists and numpy for the same data range.


In [10]:
numpy_array = np.arange(100)
numpy_array[:5]
size_of_array = numpy_array.nbytes
print(size_of_array)

800


In [13]:
import sys
import numpy as np

# Create a Python list with a range of data
data_list = list(range(1000))

# Calculate the memory size of the list
list_size = sys.getsizeof(data_list) 

# Create a NumPy array with the same data
data_array = np.array(data_list)

# Calculate the memory size of the NumPy array
array_size = data_array.nbytes

# Print the results
print(f"Memory size of the Python list: {list_size} bytes")
print(f"Memory size of the NumPy array: {array_size} bytes")


Memory size of the Python list: 8056 bytes
Memory size of the NumPy array: 8000 bytes


##### Numpy Basic Operation

In [ ]:
import numpy as np
revq1 = np.array([1,4,6,10])
revq1
revq1.ndim ## Printing the number of dimensions of the array

1

In [25]:
revq2 = np.array([[23, 80, 56, 100], [56, 78, 89,12]]) ## should have the same number of rows and columns or else expect errors
revq2.ndim

2

In [23]:
import numpy as np

# Equal number of elements in each row
revq2 = np.array([[23, 80, 56, 100], [56, 78, 89, 0]])  # Added 0 to the second row

print(revq2)


[[ 23  80  56 100]
 [ 56  78  89   0]]


In [ ]:
## Indexing in numpy arrays
revq2[0,1] # Accessing the second element in the first row

np.int64(80)

#### Using numpy for product and price calculations

In [4]:
import numpy as np
q1 = np.array([
    [250, 150, 300], # Product A
    [340, 200, 180], # Product B
    [143, 672, 800]  # Product
])
q1

q2 = np.array([
    [145, 180, 700],
    [120, 210, 652],
    [160, 210, 450]
])

q2

array([[145, 180, 700],
       [120, 210, 652],
       [160, 210, 450]])

In [ ]:
q1 + q2 # Matrix addition

array([[ 395,  330, 1000],
       [ 460,  410,  832],
       [ 303,  882, 1250]])

In [6]:
## Calculating discounts on each product
q1_discounted = q1 * 0.2
q2_discounted = q2 * 0.2


In [7]:
q1_discounted

array([[ 50. ,  30. ,  60. ],
       [ 68. ,  40. ,  36. ],
       [ 28.6, 134.4, 160. ]])

In [8]:
q2_discounted
@

array([[ 29. ,  36. , 140. ],
       [ 24. ,  42. , 130.4],
       [ 32. ,  42. ,  90. ]])

In [9]:
# Totals for the discounted
q1_total = np.sum(q1_discounted)
q1_total

np.float64(607.0)

In [13]:
b = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
# For more than one dimension, slicing to get specific numbers should include commas, not semi colon
b[2,0]

np.int64(7)

In [16]:
## Slicing in two dimensional arrays
b[:]
b[1, 0:2]

array([4, 5])

In [17]:
## Getting the index of a maximum value in numpy
monthly_sales = np.array([23, 56, 78, 100])
np.argmax(monthly_sales)

np.int64(3)

In [ ]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

: 